import "./globals.css";

import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";

import { Toaster } from "@/components/ui/sonner";

// import { Geist, Geist_Mono } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "CoreLearn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      publishableKey={
        "pk_test_ZGVjaWRpbmctZ3JvdXBlci04My5jbGVyay5hY2NvdW50cy5kZXYk"
      }
    >
      <html lang="en">
        <body className={"font-sans antialiased"}>
          <Toaster />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
